version: 2
workflows:
  version: 2
  test:
    jobs:
      - test
  commit:
    jobs:
      - audit
jobs:
  test:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: 
          name: Merge with master 
          command: |
            git config user.name "dummy"
            git config user.email "dumy@example.org"
            git fetch origin master
            git merge --squash origin/master
      - restore_cache:
          keys:
            - npm-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-modules-{{ .Branch }}-
            - npm-modules-
      - run: npm install
      # Fix error with installing @types.
      - run: rm -rf node_modules/@types/babel__core/ node_modules/@types/babel__template/
      - run: npm run lint
      - run: npm run test
      - save_cache:
          paths:
            - node_modules
          key: npm-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
  audit:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: set -o pipefail && npm audit --force 2>&1 | tee audit.log && exit 1
      - run:
          name: Audit fix
          command: npm audit fix
          when: on_fail
      - run:
          name: Create PR
          command: |
            git config --global user.email "audit@example.org"
            git config --global user.name "Audit Bot"
            git checkout -b ci/npm-audit-fix-$CIRCLE_BUILD_NUM
            git add package.json package-lock.json
            git commit -m "audit fix"
            git push origin ci/npm-audit-fix-$CIRCLE_BUILD_NUM
            hub pull-request -m "[Security] Audit Fix" -m "$(cat audit.log | tail -2)" -m "$CIRCLE_BUILD_URL"
          when: on_fail